# Generated by Django 3.1.4 on 2020-12-16 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30, verbose_name='Oras')),
                ('street', models.CharField(max_length=30, verbose_name='Strada')),
                ('street_no', models.IntegerField(verbose_name='Nr.')),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Retea')),
                ('cif', models.IntegerField(verbose_name='CUI')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nume Produs')),
                ('url_img', models.CharField(max_length=200, verbose_name='URL Img')),
                ('active_product', models.BooleanField(default=True, verbose_name='Activ')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nume Magazin')),
                ('active_shop', models.BooleanField(default=True, verbose_name='Activ')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.address')),
                ('network', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.network')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PromotionalCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nume Campanie')),
                ('start_date', models.DateField(verbose_name='Data Start')),
                ('end_date', models.DateField(verbose_name='Data Sfarsit')),
                ('active_campaign', models.BooleanField(default=False, verbose_name='Activ')),
                ('product', models.ManyToManyField(to='dashboard.Product')),
                ('shops_network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.network')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nume Premiu')),
                ('url_img', models.CharField(max_length=200, verbose_name='URL Img')),
                ('active_product', models.BooleanField(default=True, verbose_name='Activ')),
                ('quantity', models.IntegerField(default=0, verbose_name='Stoc')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.shop')),
            ],
        ),
    ]
