# Generated by Django 3.1.4 on 2020-12-21 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20201217_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionalcampaign',
            name='product',
        ),
        migrations.AddField(
            model_name='promotionalcampaign',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.product'),
            preserve_default=False,
        ),
    ]
