# Generated by Django 3.1.4 on 2021-01-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20201221_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='prize',
            name='max',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='prize',
            name='min',
            field=models.IntegerField(default=0),
        ),
    ]
