# Generated by Django 3.1.4 on 2021-01-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20210102_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='max',
            field=models.IntegerField(default=0),
        ),
    ]
