# Generated by Django 3.1.4 on 2021-01-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210103_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionalcampaign',
            name='product',
        ),
        migrations.AddField(
            model_name='promotionalcampaign',
            name='product',
            field=models.ManyToManyField(to='dashboard.Product'),
        ),
    ]
