# Generated by Django 3.1.4 on 2021-01-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210103_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionalcampaign',
            name='end_date',
            field=models.DateTimeField(verbose_name='Data Sfarsit'),
        ),
        migrations.AlterField(
            model_name='promotionalcampaign',
            name='start_date',
            field=models.DateTimeField(verbose_name='Data Start'),
        ),
    ]
