# Generated by Django 3.1.4 on 2021-01-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20210105_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionalcampaign',
            name='prize',
            field=models.ManyToManyField(to='dashboard.Prize'),
        ),
    ]
