# Generated by Django 3.1.4 on 2021-01-17 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20210117_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionalcampaign',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='promotional_campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.promotionalcampaign'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='network',
            name='cif',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='prize',
            name='active_product',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='prize',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='prize',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prize',
            name='url_img',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='active_product',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='url_img',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='promotionalcampaign',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='promotionalcampaign',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='promotionalcampaign',
            name='selected_campaign',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='promotionalcampaign',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='shop',
            name='active_shop',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
