# Generated by Django 3.1.4 on 2021-01-17 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20210117_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='promotional_campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.promotionalcampaign'),
        ),
    ]
