# Generated by Django 3.1.4 on 2020-12-08 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_store', models.CharField(max_length=20, verbose_name='Grup Magazin')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=30, verbose_name='Denumire')),
                ('full_name', models.CharField(max_length=30)),
                ('store_address', models.CharField(max_length=40, verbose_name='Adresa')),
                ('store_active', models.BooleanField(default=True, verbose_name='Activ')),
                ('allocate_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group_store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.groupstore')),
            ],
            options={
                'ordering': ['store_name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20, verbose_name='Denumire')),
                ('url_img', models.CharField(max_length=200, verbose_name='URL Img')),
                ('product_active', models.BooleanField(default=True, verbose_name='Activ')),
                ('stock', models.IntegerField(verbose_name='Stoc')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.store')),
            ],
            options={
                'ordering': ['product_name'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_name', models.CharField(max_length=50, verbose_name='Denumire')),
                ('campaign_start_date', models.DateField(verbose_name='Data Start')),
                ('campaign_end_date', models.DateField(verbose_name='Data Sfarsit')),
                ('campaign_active', models.BooleanField(default=False, verbose_name='Activ')),
                ('product', models.ManyToManyField(to='website.Product')),
            ],
            options={
                'ordering': ['campaign_name'],
            },
        ),
    ]
