# Generated by Django 3.1.4 on 2020-12-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20, verbose_name='Denumire')),
                ('url_img', models.CharField(max_length=200, verbose_name='URL Img')),
                ('product_active', models.BooleanField(default=True, verbose_name='Activ')),
            ],
        ),
    ]
