# Generated by Django 3.1.4 on 2020-12-02 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20201202_2115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['campaign_name']},
        ),
    ]
