# Generated by Django 3.1.4 on 2021-01-03 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='ticket_date',
            field=models.DateTimeField(verbose_name='Data Bon'),
        ),
    ]
