# Generated by Django 3.1.4 on 2021-01-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20210103_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='total_sale',
            field=models.IntegerField(default=0),
        ),
    ]
