# Generated by Django 3.1.4 on 2021-01-04 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20210103_1641'),
        ('transactions', '0003_sales_total_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='promotional_campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.promotionalcampaign'),
        ),
    ]
